### ISSUE TITLE
add proguard Cannot call the callback.

### ISSUE THREAD

**Issue by feng612266** [lovedise/PermissionGen#7]
add proguard Cannot call the callback,
i had add below in the proguard_rule file:
-keep class kr.co.namee.permissiongen.** { *; }
-dontwarn kr.co.namee.permissiongen.**

it can not work

**Comment by wang8651971** [comment]
try this

-keepattributes *Annotation*
-keepclassmembers class ** {
    @kr.co.namee.permissiongen.PermissionSuccess public *;
    @kr.co.namee.permissiongen.PermissionFail public *;
}

**Comment by Awent** [comment]
@wang8651971 @lovedise I tried your confusion, but the release still can not call back success or failure
