### ISSUE TITLE
Fail to request permission BIND_NOTIFICATION_LISTENER_SERVICE

### ISSUE THREAD

**Issue by OumaSyuu** [lovedise/PermissionGen#9]
Hi, is it possible to get permission “BIND_NOTIFICATION_LISTENER_SERVICE” using PermissionGen?

![image](https://cloud.githubusercontent.com/assets/14196120/20743885/a1acd4b6-b713-11e6-80e7-b4377fa7c74a.png)

Nothing pop-up.

**Comment by lovedise** [comment]
Hello @OumaSyuu 
permission can only be called from Activity or Fragment
